[project]
name = "shiny-app-eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.2",
    "matplotlib>=3.10.7",
    "polars>=1.35.2",
    "shiny>=1.5.0",
]
